export const products = [
    {
        id: '1',
        name: 'Royal Banarasi Silk Saree',
        description: 'A timeless classic, this deep maroon Banarasi silk saree features intricate gold zari work in a floral jangla pattern. Ideal for weddings, this saree drapes elegantly and exudes a regal charm.',
        price: 45000,
        category: 'Silk',
        fabric: 'Katan Silk',
        color: 'Maroon',
        blouse: 'Matching Plain Blouse with Zari Border',
        washCare: 'Dry Clean Only',
        occasion: 'Wedding',
        image: 'https://images.unsplash.com/photo-1610189012906-fac6d58f1a54?auto=format&fit=crop&q=80&w=600',
        isFeatured: true,
    },
    {
        id: '2',
        name: 'Kanjivaram Gold Tissue Saree',
        description: 'Exquisite Kanjivaram silk in a stunning gold tissue finish, woven with pure 2g zari. The border features traditional temple motifs, making it a masterpiece of Kanchi craftsmanship.',
        price: 58000,
        category: 'Silk',
        fabric: 'Pure Silk',
        color: 'Gold',
        blouse: 'Contrast Pink Blouse',
        washCare: 'Dry Clean Only',
        occasion: 'Reception',
        image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=600',
        isFeatured: true,
    },
    {
        id: '3',
        name: 'Uppada Lightweight Silk',
        description: 'Elegant and lightweight Uppada silk saree in a cream shade with delicate jamdani floral motifs. Known for its soft texture and ease of wear.',
        price: 32000,
        category: 'Silk',
        fabric: 'Uppada Silk',
        color: 'Cream',
        blouse: 'Running Blouse',
        washCare: 'Dry Clean Only',
        occasion: 'Festive',
        image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=600',
        isFeatured: true,
    },
    {
        id: '4',
        name: 'Handloom Cotton Ikat',
        description: 'Authentic handloom cotton saree featuring traditional Ikat geometric patterns in earthy tones. breathable and perfect for office wear.',
        price: 4500,
        category: 'Cotton',
        fabric: 'Mercerized Cotton',
        color: 'Grey/Red',
        blouse: 'Running Blouse',
        washCare: 'Hand Wash Cold',
        occasion: 'Casual',
        image: 'https://images.unsplash.com/photo-1544441893-675973e30605?auto=format&fit=crop&q=80&w=600',
        isFeatured: false,
    },
    {
        id: '5',
        name: 'Gadwal Silk Cotton',
        description: 'A beautiful blend of silk and cotton body with a pure silk kuttu border. This Gadwal saree showcases a contrasting blue border and pallu against a yellow body.',
        price: 12000,
        category: 'Handloom',
        fabric: 'Sico (Silk Cotton)',
        color: 'Yellow/Blue',
        blouse: 'Contrast Blue Blouse',
        washCare: 'Dry Clean Only',
        occasion: 'Festive',
        image: 'https://images.unsplash.com/photo-1610030469668-93510cb67655?auto=format&fit=crop&q=80&w=600',
        isFeatured: true,
    },
    {
        id: '6',
        name: 'Paithani Silk Saree',
        description: 'Traditional Paithani saree with a peacock design (Mor Bangadi) on the pallu and a kaleidoscope of colors. A staple in Maharashtrian weddings.',
        price: 65000,
        category: 'Silk',
        fabric: 'Pure Paithani Silk',
        color: 'Purple',
        blouse: 'Matching Blouse',
        washCare: 'Dry Clean Only',
        occasion: 'Wedding',
        image: 'https://images.unsplash.com/photo-1590736961958-51fdc62bad13?auto=format&fit=crop&q=80&w=600',
        isFeatured: true,
    }
];

export const categories = [
    { name: 'Silk', slug: 'silk', image: 'https://images.unsplash.com/photo-1610189012906-fac6d58f1a54?auto=format&fit=crop&q=80&w=600' },
    { name: 'Cotton', slug: 'cotton', image: 'https://images.unsplash.com/photo-1544441893-675973e30605?auto=format&fit=crop&q=80&w=600' },
    { name: 'Handloom', slug: 'handloom', image: 'https://images.unsplash.com/photo-1610030469668-93510cb67655?auto=format&fit=crop&q=80&w=600' },
];
