export const products = [
    {
        id: '1',
        name: 'Royal Banarasi Silk Saree',
        description: 'A timeless classic, this deep maroon Banarasi silk saree features intricate gold zari work in a floral jangla pattern. Ideal for weddings.',
        price: 45000,
        category: 'Silk',
        fabric: 'Katan Silk',
        color: 'Maroon',
        blouse: 'Matching Plain Blouse',
        washCare: 'Dry Clean Only',
        occasion: 'Wedding',
        image: 'https://images.unsplash.com/photo-1610189012906-fac6d58f1a54?auto=format&fit=crop&q=80&w=600',
        isFeatured: true,
    },
    {
        id: '2',
        name: 'Kanjivaram Gold Tissue Saree',
        description: 'Exquisite Kanjivaram silk in a stunning gold tissue finish, woven with pure 2g zari. A masterpiece of Kanchi craftsmanship.',
        price: 58000,
        category: 'Silk',
        fabric: 'Pure Silk',
        color: 'Gold',
        blouse: 'Contrast Pink Blouse',
        washCare: 'Dry Clean Only',
        occasion: 'Reception',
        image: 'https://images.unsplash.com/photo-1610189012906-fac6d58f1a54?auto=format&fit=crop&q=80&w=600',
        isFeatured: true,
    },
    {
        id: '3',
        name: 'Uppada Lightweight Silk',
        description: 'Elegant and lightweight Uppada silk saree in a cream shade with delicate floral motifs.',
        price: 32000,
        category: 'Silk',
        fabric: 'Uppada Silk',
        color: 'Cream',
        blouse: 'Running Blouse',
        washCare: 'Dry Clean Only',
        occasion: 'Festive',
        image: 'https://images.unsplash.com/photo-1610189012906-fac6d58f1a54?auto=format&fit=crop&q=80&w=600',
        isFeatured: true,
    },
    {
        id: '4',
        name: 'Handloom Cotton Ikat',
        description: 'Authentic handloom cotton saree featuring traditional Ikat patterns in earthy tones.',
        price: 4500,
        category: 'Cotton',
        fabric: 'Mercerized Cotton',
        color: 'Grey/Red',
        blouse: 'Running Blouse',
        washCare: 'Hand Wash Cold',
        occasion: 'Casual',
        image: 'https://images.unsplash.com/photo-1610189012906-fac6d58f1a54?auto=format&fit=crop&q=80&w=600',
        isFeatured: false,
    },
    {
        id: '5',
        name: 'Gadwal Silk Cotton',
        description: 'A beautiful blend of silk and cotton body with a pure silk kuttu border.',
        price: 12000,
        category: 'Handloom',
        fabric: 'Sico',
        color: 'Yellow/Blue',
        blouse: 'Contrast Blouse',
        washCare: 'Dry Clean Only',
        occasion: 'Festive',
        image: 'https://images.unsplash.com/photo-1610189012906-fac6d58f1a54?auto=format&fit=crop&q=80&w=600',
        isFeatured: true,
    },
    {
        id: '6',
        name: 'Paithani Silk Saree',
        description: 'Traditional Paithani saree with a peacock design on the pallu and a kaleidoscope of colors.',
        price: 65000,
        category: 'Silk',
        fabric: 'Paithani Silk',
        color: 'Purple',
        blouse: 'Matching Blouse',
        washCare: 'Dry Clean Only',
        occasion: 'Wedding',
        image: 'https://images.unsplash.com/photo-1610189012906-fac6d58f1a54?auto=format&fit=crop&q=80&w=600',
        isFeatured: true,
    }
];

export const categories = [
    { name: 'Silk', slug: 'silk', image: 'https://placehold.co/300x200/5E0B15/FFF?text=Silk' },
    { name: 'Cotton', slug: 'cotton', image: 'https://placehold.co/300x200/FDFBF7/000?text=Cotton' },
    { name: 'Handloom', slug: 'handloom', image: 'https://placehold.co/300x200/D4AF37/000?text=Handloom' },
];
